title:Pawar Jyoti
#logo:https://www.google.com/imgres?q=logo%20as%20full%20stack%20developer&imgurl=https%3A%2F%2Fmiro.medium.com%2Fv2%2Fresize%3Afit%3A1110%2F0*A2s5TI5LrD6UPRQt.jpg&imgrefurl=https%3A%2F%2Fmedium.com%2Fclub-infosphere%2Ffull-stack-web-developer-a-guide-to-learn-787aaf659bfa&docid=F13820e94aFMmM&tbnid=YOAvLbTsWUWjZM&vet=12ahUKEwilnqTu9byIAxVu3jgGHbbjO3cQM3oECFEQAA..i&w=1110&h=550&hcb=2&ved=2ahUKEwilnqTu9byIAxVu3jgGHbbjO3cQM3oECFEQAA
#description:Engineer who works on the entire development process of websites and applications, from start to finish.
#show_downloads:true
theme:jekyll-theme-minimal
